-- Contadores de janela móvel usados exclusivamente para proteger o Webchat.
CREATE TABLE IF NOT EXISTS n016 (
    cod016 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chv016 VARCHAR(180) NOT NULL,
    jan016 TIMESTAMP WITH TIME ZONE NOT NULL,
    qtd016 INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_n016_quantidade CHECK (qtd016 >= 0),
    CONSTRAINT uq_n016_chave_janela UNIQUE (chv016, jan016)
);

CREATE INDEX IF NOT EXISTS ix_n016_janela
    ON n016 (jan016);

COMMENT ON TABLE n016 IS
'Contadores temporários de limite de requisições do Webchat por IP e sessão.';
