CREATE TABLE IF NOT EXISTS n021 (
    cod021 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod001 BIGINT NOT NULL REFERENCES n001(cod001) ON UPDATE CASCADE ON DELETE CASCADE,
    cod002 BIGINT NOT NULL REFERENCES n002(cod002) ON UPDATE CASCADE ON DELETE CASCADE,
    cad021 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_n021_empresa_usuario UNIQUE (cod001, cod002)
);

CREATE INDEX IF NOT EXISTS ix_n021_usuario_empresa ON n021 (cod002, cod001);

COMMENT ON TABLE n021 IS 'Primeira visualização do contrato de licença por supervisor e empresa.';
COMMENT ON COLUMN n021.cod001 IS 'Empresa cujo contrato foi exibido.';
COMMENT ON COLUMN n021.cod002 IS 'Supervisor que visualizou o contrato.';
COMMENT ON COLUMN n021.cad021 IS 'Data e hora da primeira visualização do contrato.';
